version: '3.3'

services:
    reverse-proxy:
        image: traefik:${TRAEFIK_VERSION}
        container_name: traefik
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        labels:
            - "traefik.enable=true"
        networks:
            - web
networks:
    web:
        external: true
