services:
    reverse-proxy:
        volumes:
            - ./config_dev:/etc/traefik
            - ./certs/:/etc/certs:ro
        labels:
            - "traefik.http.routers.api.rule=Host(`prod.fullfrontend.test`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        depends_on:
            -   mkcert

    mkcert:
        image: fullfrontend/mkcert
        environment:
            domain: "*.test,*.fullfrontend.test,fullfrontend.test,penpot.test,omnitools.test,silviattitude.test,n8n.test,open-webui.test,elementor.test,example.elementor.test,phpmyadmin.elementor.test"
        volumes:
            - ./certs/:/root/.local/share/mkcert
        labels:
            - "traefik.enable=false"
        networks:
            - web