version: 2
jobs:
    deploy:
        machine:
            enabled: true
        steps:
            -   run:
                    name: "Deploy Traefik example stack"
                    command: |
                        ssh "${PROD_SERVER_USER}@${PROD_SERVER_HOST}" "cd ${PROD_SERVER_PATH} && git pull --rebase && APP_ENV=prod ./deploy.sh"

workflows:
    version: 2
    deploy:
        jobs:
            -   deploy:
                    context: 'Production Server'
                    filters:
                        branches:
                            only: master
